<?include_once("newcoms/Database.php");
include_once("newcoms/function.php");
$domain_name= $_SERVER["HTTP_HOST"] ;
$url=$_SERVER["REQUEST_URI"];
$temp=explode(".",$domain_name);
if($temp[0]=="www")
unset($temp[0]);
if($domain_name="localhost")
$domain_name="";
$site=(count($temp)<=2&&count($temp)>=0||count($temp)==4) ? "main" : $temp[0];
$url_temp=explode("/",$url);
$query5="select  title  from new_language where status=1";
$result5 = $coms_conect->query($query5);
while($RS15 = $result5->fetch_assoc()){
	$lang_array[]=$RS15["title"];
}
if(count($url_temp)==2){
	if($url_temp[1]=="logout"){
	include("new_dynamics/new_logout.php4");exit;;
	}
	if($url_temp[1]=="new_login"){
	include("new_login.php");exit;;
	}
	if($url_temp[1]=="coms"){
	include("new_login.php");exit;;
	}
	if($url_temp[1]=="newcoms"){
	include("newcoms/index2.php4");exit;;
	}
	if(in_array($url_temp[1],$lang_array)){;
	$madual_lang=injection_replace($url_temp[1]);;
	include_once("new_home.php");exit;;
	}else{;
	$user_username=$url_temp[1];;
	include("new_dynamics/default/new_user_profile_page.php4");exit;;
		};
}
if(count($url_temp)==3){
	if($url_temp[1]=="coms"){
	include("new_login.php");exit;;
	}
	if($url_temp[1]=="logout"){
	include("new_dynamics/new_logout.php4");exit;;
	}
	if($url_temp[1]=="contact_us"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_contact_us";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="doctors"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_docters";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="brand"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_profile_tem";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="catalog"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_catalog";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="company"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_company_tem";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="products"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_products";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="product"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_product";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="cart"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_cart";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="pay"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_pay_cart";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="category"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_category";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="adwords"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_adwords";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="ssl"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_ssl";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="domain"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_domain";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="host"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_host";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="vps"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_vps";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="dedicated-server"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_dedicated_server";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="sms"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_sms";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="rhinoplasty"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_rhinoplasty";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="bony-nose-surgery"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_bony_nose_surgery";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="otoplasty"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_otoplasty";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="drsheikhi-p1"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_drsheikhi_p1";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="drsheikhi-p2"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_drsheikhi_p2";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="drsheikhi-p3"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_drsheikhi_p3";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="drsheikhi-p4"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_drsheikhi_p4";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="drsheikhi-p5"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_drsheikhi_p5";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="drsheikhi-p6"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_drsheikhi_p6";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="drsheikhi-p7"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_drsheikhi_p7";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="drsheikhi-p8"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_drsheikhi_p7";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="drsheikhi-p9"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_drsheikhi_p7";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="drsheikhi-p10"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_drsheikhi_p7";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="drsheikhi-p11"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_drsheikhi_p11";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="drsheikhi-p12"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_drsheikhi_p12";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="drsheikhi-p13"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_drsheikhi_p13";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="drsheikhi-p14"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_drsheikhi_p14";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="drsheikhi-p15"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_drsheikhi_p15";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="Occupational-therapy"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_rasesh_p1";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="Speech-therapy"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_rasesh_p2";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="Dark-room"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_rasesh_p3";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="Play-therapy"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_rasesh_p4";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="Group-therapy"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_rasesh_p5";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="intohost"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_intohost";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="dedicated"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_dedicated";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="dedicatedserver-nvme"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_dedicatedserver_nvme";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="startup"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_startup";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="android-app-development"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_android_app_development";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="ios-app-development"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_ios_app_development";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="license"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_license";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="about"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_about";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="education"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_education";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="webpack"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_webpack";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="android"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_android";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="reset_password"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="reset_password";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="add_ads"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_add_ads";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="price"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_price";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="faq"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_faq";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="question"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_question";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="mansger_sms_login"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_mansger_sms_login";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="sms_validation"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_user_sms_validation";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="login"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_user_login";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="profile"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_user_profile";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="ProfileShow"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_ProfileShow_EB";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="panel"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_user_profile_panel";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="register"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_register";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="sms_login"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_user_login_sms";
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="rss"){
		$madual_lang=injection_replace($url_temp[2]);
		$madual_file_name="new_rss";
		include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=='news'){
		$madual_file_name='new_news';
		$madual_lang=injection_replace($url_temp[2]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='fotter'){
		$madual_file_name='';
		$madual_lang=injection_replace($url_temp[2]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='product'){
		$madual_file_name='new_product';
		$madual_lang=injection_replace($url_temp[2]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='page'){
		$madual_file_name='';
		$madual_lang=injection_replace($url_temp[2]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='download'){
		$madual_file_name='new_download';
		$madual_lang=injection_replace($url_temp[2]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='article'){
		$madual_file_name='new_article';
		$madual_lang=injection_replace($url_temp[2]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='video'){
		$madual_file_name='new_video';
		$madual_lang=injection_replace($url_temp[2]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='gallery'){
		$madual_file_name='new_gallery';
		$madual_lang=injection_replace($url_temp[2]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='blog'){
		$madual_file_name='new_blog';
		$madual_lang=injection_replace($url_temp[2]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='content'){
		$madual_file_name='new_content';
		$madual_lang=injection_replace($url_temp[2]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='company'){
		$madual_file_name='new_company';
		$madual_lang=injection_replace($url_temp[2]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='agahi'){
		$madual_file_name='new_agahi';
		$madual_lang=injection_replace($url_temp[2]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='doctor'){
		$madual_file_name='new_doctor_text';
		$madual_lang=injection_replace($url_temp[2]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='catalog'){
		$madual_file_name='new_catalog';
		$madual_lang=injection_replace($url_temp[2]);
		include("new_dynamic.php");exit;	
	}
		$madual_lang=injection_replace($url_temp[2]);
		$name=injection_replace($url_temp[1]);
}
if(count($url_temp)==4){
	$array=explode("?",$url_temp[3]);
	if(count($array)==2){
		$madual_lang=injection_replace($url_temp[2]);
		$madual_file_name="new_content";
		include("new_dynamic.php");exit;;
	}
	if($url_temp[2]=="page"){
		$madual_lang=injection_replace($url_temp[1]);
		$madual_page_id=injection_replace($url_temp[3]);
		include("new_home.php");exit;;
	}
	if($url_temp[1]=="rss"){
		$madual_lang=injection_replace($url_temp[2]);
		$rss_id=injection_replace($url_temp[3]);
		$madual_file_name="new_show_rss";
		include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="category"){
		$madual_lang=injection_replace($url_temp[2]);
		$url_temp[3]=="name";
		$madual_file_name="new_under_cat";
		include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="product"){
		$madual_lang=injection_replace($url_temp[2]);
		$url_temp[3]=="name";
		$madual_file_name="new_under_product";
		include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="brand"){
		$madual_lang=injection_replace($url_temp[2]);
		$url_temp[3]=="catalog";
		$madual_file_name="new_catalog_tem";
		include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="login"){
		$madual_lang=injection_replace($url_temp[2]);
		$active_email_id=injection_replace($url_temp[3]);
		$madual_file_name="new_user_login";
		include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="news"&&$url_temp[3]=="tag"){
		$madual_lang=injection_replace($url_temp[2]);
		//$rss_id=injection_replace($url_temp[3]);
		$madual_file_name="new_news_tag";
		include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="faq"&&$url_temp[3]=="new"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_faq_new";
	$faqq=injection_replace($url_temp[3]);
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="question"&&$url_temp[3]=="new"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_question_new";
	$faqq=injection_replace($url_temp[3]);
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="search"){
		$madual_lang=injection_replace($url_temp[2]);
		$rss_id=injection_replace($url_temp[3]);
		$madual_file_name="new_Search";
		include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=='news'){
		$madual_file_name='new_news_text';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='fotter'){
		$madual_file_name='newsss';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='product'){
		$madual_file_name='new_product_text';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='page'){
		$madual_file_name='newsss';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='download'){
		$madual_file_name='new_download_show';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='article'){
		$madual_file_name='new_article_show';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='video'){
		$madual_file_name='new_video_show';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='gallery'){
		$madual_file_name='new_gallery_show';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='blog'){
		$madual_file_name='new_blog_show';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='content'){
		$madual_file_name='new_content_text';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='company'){
		$madual_file_name='new_company_text';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='agahi'){
		$madual_file_name='new_agahi_text';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='doctor'){
		$madual_file_name='new_doctor_text';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[1]=='catalog'){
		$madual_file_name='new_catalog_text';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
$madual_id=injection_replace($url_temp[1]);
$madual_lang=injection_replace($url_temp[2]);
$name=injection_replace($url_temp[1]);
}
if(count($url_temp)==5){
	if($url_temp[1]=="ProfileShow"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_ProfileShow_EB";
$madual_page_id=injection_replace($url_temp[3]);
$search_module=injection_replace($url_temp[4]);
	include("new_dynamic.php");exit;;
	}
	$array=explode("?",$url_temp[4]);
	if(count($array)==2){
		$madual_lang=injection_replace($url_temp[2]);
		$madual_file_name="new_catalog_tem";
		include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="search"){
		$madual_lang=injection_replace($url_temp[2]);
		$q=injection_replace($url_temp[3]);
		$search_module=injection_replace($url_temp[4]);
		$madual_file_name="new_Search";
		include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="faq"&&$url_temp[3]=="category"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_faq";
	$cat_id=injection_replace($url_temp[4]);
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="question"&&$url_temp[3]=="category"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_question";
	$cat_id=injection_replace($url_temp[4]);
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="faq"&&$url_temp[3]=="page"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_faq";
	$faq_page=injection_replace($url_temp[4]);
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="question"&&$url_temp[3]=="page"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_question";
	$faq_page=injection_replace($url_temp[4]);
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="faq"&&$url_temp[3]=="tag"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_faq";
	$tag=injection_replace($url_temp[4]);
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="question"&&$url_temp[3]=="tag"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_question";
	$tag=injection_replace($url_temp[4]);
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="faq"&&$url_temp[3]=="search"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_faq";
	$sreach_id=injection_replace($url_temp[4]);
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="question"&&$url_temp[3]=="search"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_question";
	$sreach_id=injection_replace($url_temp[4]);
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="faq"&&$url_temp[3]=="show"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_faq_show";
	$faq_id=injection_replace($url_temp[4]);
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="question"&&$url_temp[3]=="show"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_question_show";
	$faq_id=injection_replace($url_temp[4]);
	include("new_dynamic.php");exit;;
	}
   if($url_temp[1]=="profile"&&$url_temp[3]=="ticket"&&$url_temp[4]=="show"){
        $ticket_id=$url_temp[5];
        $madual_lang=injection_replace($url_temp[2]);
        $madual_file_name="new_user_profile";
        $madual_main_file="new_showall_ticket";
		include("new_dynamic.php");exit;
	}
	if($url_temp[3]=="pm"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_user_profile";
	$madual_page_id=injection_replace($url_temp[4]);
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="keyword"&&$url_temp[3]!="page"){
		$madual_file_name="new_show_comments";
		$madual_lang=injection_replace($url_temp[3]);
		$madual_page_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[2]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[3]=="page"&&$url_temp[1]=='news'){
		$madual_file_name='new_news';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_page_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if($url_temp[3]=="category"&&$url_temp[1]=='news'){
		$madual_file_name='new_news_cat';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_cat_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]=="search"&&$url_temp[1]=='news')||($url_temp[3]=="keyword"&&$url_temp[1]=='news')){
		$madual_file_name='new_news_keyword';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_search_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[3]=="page"&&$url_temp[1]=='fotter'){
		$madual_file_name='';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_page_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if($url_temp[3]=="category"&&$url_temp[1]=='fotter'){
		$madual_file_name='caat';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_cat_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]=="search"&&$url_temp[1]=='fotter')||($url_temp[3]=="keyword"&&$url_temp[1]=='fotter')){
		$madual_file_name='';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_search_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[3]=="page"&&$url_temp[1]=='product'){
		$madual_file_name='new_product';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_page_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if($url_temp[3]=="category"&&$url_temp[1]=='product'){
		$madual_file_name='new_product_cat';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_cat_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]=="search"&&$url_temp[1]=='product')||($url_temp[3]=="keyword"&&$url_temp[1]=='product')){
		$madual_file_name='new_product_search';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_search_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[3]=="page"&&$url_temp[1]=='page'){
		$madual_file_name='';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_page_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if($url_temp[3]=="category"&&$url_temp[1]=='page'){
		$madual_file_name='new_page_cat';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_cat_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]=="search"&&$url_temp[1]=='page')||($url_temp[3]=="keyword"&&$url_temp[1]=='page')){
		$madual_file_name='';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_search_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[3]=="page"&&$url_temp[1]=='download'){
		$madual_file_name='new_download';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_page_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if($url_temp[3]=="category"&&$url_temp[1]=='download'){
		$madual_file_name='new_download_cat';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_cat_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]=="search"&&$url_temp[1]=='download')||($url_temp[3]=="keyword"&&$url_temp[1]=='download')){
		$madual_file_name='new_download_search';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_search_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[3]=="page"&&$url_temp[1]=='article'){
		$madual_file_name='new_article';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_page_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if($url_temp[3]=="category"&&$url_temp[1]=='article'){
		$madual_file_name='new_article_cat';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_cat_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]=="search"&&$url_temp[1]=='article')||($url_temp[3]=="keyword"&&$url_temp[1]=='article')){
		$madual_file_name='new_article_search';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_search_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[3]=="page"&&$url_temp[1]=='video'){
		$madual_file_name='new_video';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_page_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if($url_temp[3]=="category"&&$url_temp[1]=='video'){
		$madual_file_name='new_video_cat';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_cat_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]=="search"&&$url_temp[1]=='video')||($url_temp[3]=="keyword"&&$url_temp[1]=='video')){
		$madual_file_name='new_video_keyword';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_search_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[3]=="page"&&$url_temp[1]=='gallery'){
		$madual_file_name='new_gallery';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_page_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if($url_temp[3]=="category"&&$url_temp[1]=='gallery'){
		$madual_file_name='new_gallery_cat';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_cat_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]=="search"&&$url_temp[1]=='gallery')||($url_temp[3]=="keyword"&&$url_temp[1]=='gallery')){
		$madual_file_name='new_gallery_keyword';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_search_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[3]=="page"&&$url_temp[1]=='blog'){
		$madual_file_name='new_blog';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_page_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if($url_temp[3]=="category"&&$url_temp[1]=='blog'){
		$madual_file_name='new_blog_cat';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_cat_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]=="search"&&$url_temp[1]=='blog')||($url_temp[3]=="keyword"&&$url_temp[1]=='blog')){
		$madual_file_name='new_blog_search';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_search_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[3]=="page"&&$url_temp[1]=='content'){
		$madual_file_name='new_content';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_page_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if($url_temp[3]=="category"&&$url_temp[1]=='content'){
		$madual_file_name='new_content_cat';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_cat_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]=="search"&&$url_temp[1]=='content')||($url_temp[3]=="keyword"&&$url_temp[1]=='content')){
		$madual_file_name='new_content_keyword';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_search_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[3]=="page"&&$url_temp[1]=='company'){
		$madual_file_name='new_company';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_page_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if($url_temp[3]=="category"&&$url_temp[1]=='company'){
		$madual_file_name='new_company_cat';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_cat_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]=="search"&&$url_temp[1]=='company')||($url_temp[3]=="keyword"&&$url_temp[1]=='company')){
		$madual_file_name='new_company_search';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_search_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[3]=="page"&&$url_temp[1]=='agahi'){
		$madual_file_name='new_agahi';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_page_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if($url_temp[3]=="category"&&$url_temp[1]=='agahi'){
		$madual_file_name='new_agahi_cat';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_cat_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]=="search"&&$url_temp[1]=='agahi')||($url_temp[3]=="keyword"&&$url_temp[1]=='agahi')){
		$madual_file_name='agahi';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_search_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[3]=="page"&&$url_temp[1]=='doctor'){
		$madual_file_name='new_doctor_text';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_page_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if($url_temp[3]=="category"&&$url_temp[1]=='doctor'){
		$madual_file_name='new_doctor_cat';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_cat_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]=="search"&&$url_temp[1]=='doctor')||($url_temp[3]=="keyword"&&$url_temp[1]=='doctor')){
		$madual_file_name='new_doctor_search';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_search_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	if($url_temp[3]=="page"&&$url_temp[1]=='catalog'){
		$madual_file_name='new_catalog';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_page_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if($url_temp[3]=="category"&&$url_temp[1]=='catalog'){
		$madual_file_name='new_catalog_cat';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_cat_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]=="search"&&$url_temp[1]=='catalog')||($url_temp[3]=="keyword"&&$url_temp[1]=='catalog')){
		$madual_file_name='new_catalog_search';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_search_id=urldecode(injection_replace($url_temp[4]));
		$madual_name=injection_replace($url_temp[1]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]!="category"&&$url_temp[1]=='news')&&($url_temp[3]!="search"&&$url_temp[1]=='news')&&($url_temp[3]!="keyword"&&$url_temp[1]=='news')){
		$madual_file_name='new_news_text';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]!="category"&&$url_temp[1]=='fotter')&&($url_temp[3]!="search"&&$url_temp[1]=='fotter')&&($url_temp[3]!="keyword"&&$url_temp[1]=='fotter')){
		$madual_file_name='newsss';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]!="category"&&$url_temp[1]=='product')&&($url_temp[3]!="search"&&$url_temp[1]=='product')&&($url_temp[3]!="keyword"&&$url_temp[1]=='product')){
		$madual_file_name='new_product_text';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]!="category"&&$url_temp[1]=='page')&&($url_temp[3]!="search"&&$url_temp[1]=='page')&&($url_temp[3]!="keyword"&&$url_temp[1]=='page')){
		$madual_file_name='newsss';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]!="category"&&$url_temp[1]=='download')&&($url_temp[3]!="search"&&$url_temp[1]=='download')&&($url_temp[3]!="keyword"&&$url_temp[1]=='download')){
		$madual_file_name='new_download_show';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]!="category"&&$url_temp[1]=='article')&&($url_temp[3]!="search"&&$url_temp[1]=='article')&&($url_temp[3]!="keyword"&&$url_temp[1]=='article')){
		$madual_file_name='new_article_show';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]!="category"&&$url_temp[1]=='video')&&($url_temp[3]!="search"&&$url_temp[1]=='video')&&($url_temp[3]!="keyword"&&$url_temp[1]=='video')){
		$madual_file_name='new_video_show';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]!="category"&&$url_temp[1]=='gallery')&&($url_temp[3]!="search"&&$url_temp[1]=='gallery')&&($url_temp[3]!="keyword"&&$url_temp[1]=='gallery')){
		$madual_file_name='new_gallery_show';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]!="category"&&$url_temp[1]=='blog')&&($url_temp[3]!="search"&&$url_temp[1]=='blog')&&($url_temp[3]!="keyword"&&$url_temp[1]=='blog')){
		$madual_file_name='new_blog_show';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]!="category"&&$url_temp[1]=='content')&&($url_temp[3]!="search"&&$url_temp[1]=='content')&&($url_temp[3]!="keyword"&&$url_temp[1]=='content')){
		$madual_file_name='new_content_text';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]!="category"&&$url_temp[1]=='company')&&($url_temp[3]!="search"&&$url_temp[1]=='company')&&($url_temp[3]!="keyword"&&$url_temp[1]=='company')){
		$madual_file_name='new_company_text';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]!="category"&&$url_temp[1]=='agahi')&&($url_temp[3]!="search"&&$url_temp[1]=='agahi')&&($url_temp[3]!="keyword"&&$url_temp[1]=='agahi')){
		$madual_file_name='new_agahi_text';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]!="category"&&$url_temp[1]=='doctor')&&($url_temp[3]!="search"&&$url_temp[1]=='doctor')&&($url_temp[3]!="keyword"&&$url_temp[1]=='doctor')){
		$madual_file_name='new_doctor_text';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
	 if(($url_temp[3]!="category"&&$url_temp[1]=='catalog')&&($url_temp[3]!="search"&&$url_temp[1]=='catalog')&&($url_temp[3]!="keyword"&&$url_temp[1]=='catalog')){
		$madual_file_name='new_catalog_text';
		$madual_lang=injection_replace($url_temp[2]);
		$madual_id=injection_replace($url_temp[3]);
		include("new_dynamic.php");exit;	
	}
}
if(count($url_temp)==6){
	if($url_temp[1]=="search"){
		$madual_lang=injection_replace($url_temp[2]);
		$q=injection_replace($url_temp[3]);
		$search_module=injection_replace($url_temp[4]);
		$search_page=injection_replace($url_temp[5]);
		$madual_file_name="new_Search";
		include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="faq"&&$url_temp[3]=="search"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_faq";
	$cat_id=injection_replace($url_temp[4]);
	$sreach_id=injection_replace($url_temp[5]);
	include("new_dynamic.php");exit;;
	}
   if($url_temp[1]=="page"&&$url_temp[3]=="keyword"){
        $keyword_id=$url_temp[4];
        $madual_page_id=$url_temp[5];
        $madual_lang=injection_replace($url_temp[2]);
        $madual_file_name="new_page_keyword";
		include("new_dynamic.php");exit;
	}
   if($url_temp[1]=="page"&&$url_temp[3]=="category"){
        $keyword_id=$url_temp[4];
        $madual_page_id=$url_temp[5];
        $madual_lang=injection_replace($url_temp[2]);
        $madual_file_name="new_page_cat";
		include("new_dynamic.php");exit;
	}
   if($url_temp[1]=="page"&&$url_temp[3]=="search"){
        $keyword_id=$url_temp[4];
        $madual_page_id=$url_temp[5];
        $madual_lang=injection_replace($url_temp[2]);
        $madual_file_name="new_page_search";
		include("new_dynamic.php");exit;
	}
   if($url_temp[1]=="profile"&&$url_temp[3]=="ads"&&$url_temp[4]=="edit"){
        $ads_edit_id=$url_temp[5];
        $madual_lang=injection_replace($url_temp[2]);
        $madual_file_name="new_user_profile";
		include("new_dynamic.php");exit;
	}
   if($url_temp[1]=="profile"&&$url_temp[3]=="ticket"&&$url_temp[4]=="show"){
        $ticket_id=$url_temp[5];
        $madual_lang=injection_replace($url_temp[2]);
        $madual_file_name="new_user_profile";
        $madual_main_file="new_show_ticket";
		include("new_dynamic.php");exit;
	}
	if($url_temp[3]=="keyword"){
		if($url_temp[1]=='news'){
			$madual_file_name='new_news_keyword';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_tag_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			$madual_cat_id="null";
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='fotter'){
			$madual_file_name='';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_tag_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			$madual_cat_id="null";
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='product'){
			$madual_file_name='new_product_search';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_tag_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			$madual_cat_id="null";
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='page'){
			$madual_file_name='';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_tag_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			$madual_cat_id="null";
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='download'){
			$madual_file_name='new_download_search';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_tag_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			$madual_cat_id="null";
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='article'){
			$madual_file_name='new_article_search';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_tag_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			$madual_cat_id="null";
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='video'){
			$madual_file_name='new_video_keyword';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_tag_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			$madual_cat_id="null";
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='gallery'){
			$madual_file_name='new_gallery_keyword';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_tag_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			$madual_cat_id="null";
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='blog'){
			$madual_file_name='new_blog_search';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_tag_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			$madual_cat_id="null";
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='content'){
			$madual_file_name='new_content_keyword';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_tag_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			$madual_cat_id="null";
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='company'){
			$madual_file_name='new_company_search';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_tag_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			$madual_cat_id="null";
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='agahi'){
			$madual_file_name='agahi';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_tag_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			$madual_cat_id="null";
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='doctor'){
			$madual_file_name='new_doctor_search';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_tag_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			$madual_cat_id="null";
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='catalog'){
			$madual_file_name='new_catalog_search';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_tag_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			$madual_cat_id="null";
			include("new_dynamic.php");exit;	
		}
}
	if($url_temp[3]=="category"){
		if($url_temp[1]=='news'){
			$madual_file_name='new_news_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='fotter'){
			$madual_file_name='caat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='product'){
			$madual_file_name='new_product_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='page'){
			$madual_file_name='new_page_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='download'){
			$madual_file_name='new_download_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='article'){
			$madual_file_name='new_article_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='video'){
			$madual_file_name='new_video_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='gallery'){
			$madual_file_name='new_gallery_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='blog'){
			$madual_file_name='new_blog_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='content'){
			$madual_file_name='new_content_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='company'){
			$madual_file_name='new_company_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='agahi'){
			$madual_file_name='new_agahi_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='doctor'){
			$madual_file_name='new_doctor_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='catalog'){
			$madual_file_name='new_catalog_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[5]);
			include("new_dynamic.php");exit;	
		}
}
}
if(count($url_temp)==7){
	if($url_temp[1]=="faq"&&$url_temp[3]=="category"&&$url_temp[5]=="page"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_faq";
	$faq_page=injection_replace($url_temp[6]);
	$cat_id=injection_replace($url_temp[4]);
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="faq"&&$url_temp[3]=="tag"&&$url_temp[5]=="page"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_faq";
	$faq_page=injection_replace($url_temp[6]);
	$tag=injection_replace($url_temp[4]);
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="question"&&$url_temp[3]=="category"&&$url_temp[5]=="page"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_question";
	$faq_page=injection_replace($url_temp[6]);
	$cat_id=injection_replace($url_temp[4]);
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="question"&&$url_temp[3]=="tag"&&$url_temp[5]=="page"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_question";
	$faq_page=injection_replace($url_temp[6]);
	$tag=injection_replace($url_temp[4]);
	include("new_dynamic.php");exit;;
	}
	if($url_temp[1]=="profile"){
	$madual_lang=injection_replace($url_temp[2]);
	$madual_file_name="new_user_profile";
	$sreach_value=injection_replace($url_temp[5]);
	include("new_dynamic.php");exit;;
	}
	if($url_temp[3]=="category"&&$url_temp[5]=="page"){
		if($url_temp[1]=='news'){
			$madual_file_name='new_news_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='fotter'){
			$madual_file_name='caat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='product'){
			$madual_file_name='new_product_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='page'){
			$madual_file_name='new_page_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='download'){
			$madual_file_name='new_download_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='article'){
			$madual_file_name='new_article_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='video'){
			$madual_file_name='new_video_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='gallery'){
			$madual_file_name='new_gallery_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='blog'){
			$madual_file_name='new_blog_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='content'){
			$madual_file_name='new_content_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='company'){
			$madual_file_name='new_company_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='agahi'){
			$madual_file_name='new_agahi_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='doctor'){
			$madual_file_name='new_doctor_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='catalog'){
			$madual_file_name='new_catalog_cat';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_cat_id=injection_replace($url_temp[4]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
	}
	if(($url_temp[3]=="search")||($url_temp[3]=="keyword")){
		if($url_temp[1]=='news'){
			$madual_file_name='new_news_keyword';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_search_str=urldecode(injection_replace($url_temp[4]));
			$madual_cat_id=injection_replace($url_temp[5]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='fotter'){
			$madual_file_name='';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_search_str=urldecode(injection_replace($url_temp[4]));
			$madual_cat_id=injection_replace($url_temp[5]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='product'){
			$madual_file_name='new_product_search';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_search_str=urldecode(injection_replace($url_temp[4]));
			$madual_cat_id=injection_replace($url_temp[5]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='page'){
			$madual_file_name='';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_search_str=urldecode(injection_replace($url_temp[4]));
			$madual_cat_id=injection_replace($url_temp[5]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='download'){
			$madual_file_name='new_download_search';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_search_str=urldecode(injection_replace($url_temp[4]));
			$madual_cat_id=injection_replace($url_temp[5]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='article'){
			$madual_file_name='new_article_search';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_search_str=urldecode(injection_replace($url_temp[4]));
			$madual_cat_id=injection_replace($url_temp[5]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='video'){
			$madual_file_name='new_video_keyword';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_search_str=urldecode(injection_replace($url_temp[4]));
			$madual_cat_id=injection_replace($url_temp[5]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='gallery'){
			$madual_file_name='new_gallery_keyword';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_search_str=urldecode(injection_replace($url_temp[4]));
			$madual_cat_id=injection_replace($url_temp[5]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='blog'){
			$madual_file_name='new_blog_search';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_search_str=urldecode(injection_replace($url_temp[4]));
			$madual_cat_id=injection_replace($url_temp[5]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='content'){
			$madual_file_name='new_content_keyword';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_search_str=urldecode(injection_replace($url_temp[4]));
			$madual_cat_id=injection_replace($url_temp[5]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='company'){
			$madual_file_name='new_company_search';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_search_str=urldecode(injection_replace($url_temp[4]));
			$madual_cat_id=injection_replace($url_temp[5]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='agahi'){
			$madual_file_name='agahi';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_search_str=urldecode(injection_replace($url_temp[4]));
			$madual_cat_id=injection_replace($url_temp[5]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='doctor'){
			$madual_file_name='new_doctor_search';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_search_str=urldecode(injection_replace($url_temp[4]));
			$madual_cat_id=injection_replace($url_temp[5]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
		if($url_temp[1]=='catalog'){
			$madual_file_name='new_catalog_search';
			$madual_lang=injection_replace($url_temp[2]);
			$madual_search_str=urldecode(injection_replace($url_temp[4]));
			$madual_cat_id=injection_replace($url_temp[5]);
			$madual_page_id=injection_replace($url_temp[6]);
			include("new_dynamic.php");exit;	
		}
	}
   if($url_temp[1]=="gallery"){
        $madual_lang=injection_replace($url_temp[2]);
        $madual_id=$url_temp[3];
        $madual_title_gallery=$url_temp[4];
        $madual_page_id=$url_temp[6];
        $madual_file_name="new_gallery_show";
		include("new_dynamic.php");exit;
	}
   if($url_temp[1]=="video"){
        $madual_lang=injection_replace($url_temp[2]);
        $madual_id=$url_temp[3];
        $madual_title_video=$url_temp[4];
        $madual_page_id=$url_temp[6];
        $madual_file_name="new_video_show";
		include("new_dynamic.php");exit;
	}
}
if(count($url_temp)==8){
   if($url_temp[1]=="gallery" && $url_temp[3]=="category"){
        $madual_lang=injection_replace($url_temp[2]);
        $madual_cat_id=$url_temp[4];
        $madual_title_gallery=$url_temp[5];
        $madual_page_id=$url_temp[7];
        $madual_file_name="new_gallery_cat";
		include("new_dynamic.php");exit;
	}
   if($url_temp[1]=="gallery" && $url_temp[3]=="keyword"){
        $madual_lang=injection_replace($url_temp[2]);
        $madual_tag_id=$url_temp[4];
        $madual_title_gallery=$url_temp[5];
        $madual_page_id=$url_temp[7];
        $madual_file_name="new_gallery_keyword";
		include("new_dynamic.php");exit;
}
   if($url_temp[1]=="video" && $url_temp[3]=="category"){
        $madual_lang=injection_replace($url_temp[2]);
        $madual_cat_id=$url_temp[4];
        $madual_title_video=$url_temp[5];
        $madual_page_id=$url_temp[7];
        $madual_file_name="new_video_cat";
		include("new_dynamic.php");exit;
	}
   if($url_temp[1]=="video" && $url_temp[3]=="keyword"){
        $madual_lang=injection_replace($url_temp[2]);
        $madual_tag_id=$url_temp[4];
        $madual_title_video=$url_temp[5];
        $madual_page_id=$url_temp[7];
        $madual_file_name="new_video_keyword";
		include("new_dynamic.php");exit;
}
}
